### ISSUE TITLE
Aspect Ratio - C & D

### ISSUE THREAD

**Issue by Spawk-HS** [thebezelproject/bezelproject-MAME#8] opened 2020-04-22 03:49 UTC
I only found 2 wrong aspect in the C's:

congo
cosmica

Early in the D's I come across darius and darius2. These are ultra wide screen games so all the artwork should be on top and bottom with the actual gameplay area taking up the entire width of the screen. Probably will need a custom frame since the odd ratio???

This leads me to a title called "ddungeon". Now I really don't want to seem critical of someone else's work, but this overlay is just bad. Possibly it resembles the actual cab??? I don't know but whatever that is with the screens in each corner and the super lo-res logo in the middle... just no! There has to be some level of acceptability. I don't really care either way, the game is not good enough to stay in my collection.

Anyway there are only 3 more D's:

devzone
digger
dorachan

Just want to mention BTW that I am not testing every single bezel in this collection. I have a set built for the mame2003plus core that I trimming down to just my own "best of" and just happen to be semi testing the bezels at the same time.

**Comment by thebezelproject** [comment] 2020-04-23 07:20
congo, cosmica, devzone, digger and dorachan should be fixed in the latest MAME repo as of April 9th 2020. Have you either reinstalled MAME, or downloaded those png files directly?

Yes, ddungeon isn't the greatest. The problem is there is no art for that game except the marquee, and it was used for the logo in the middle you referenced. I can add it to the rework queue, but that seems to be unending and I couldn't say when it would be done.

**Comment by Spawk-HS** [comment] 2020-04-23 07:36
I am pretty new around here, not exactly sure when I dl'd but it was all done with windows version of the utility, synced for rocketlauncher.

Eventually I am going to have to at least try to "fix" some of these once I get my list narrowed down. I don't look forward to this as I am not very good with graphics... no PS here, just gimp. darius 1 and 2 for sure. There are a few others that have odd stuff going on like Fatal Fury 2 and 3. This weird doubling of the image on the left. I am also not a fan of the ones that have that double (or overlapping) bezel frame going on.

While I am here, the only E bezel that was wrong AR was:

eggor

**Comment by thebezelproject** [comment] 2020-04-23 07:45
Eggor was update earlier in the month. Looks like each time you find one, check on the Gitrepo MAME repo for updated files.

I've added darius and darius2 to the work queue. Again, not sure when they will be uploaded.

**Comment by Spawk-HS** [comment] 2020-04-23 08:09
ok, have a look at fatfury2 and fatfury3... 

like I said I am not great with art stuff but here is a "quick fix" of fatfury2:
[https://mega.nz/file/h74gQQ4S#E5KBKgd9aAW4YI9HXCi7F-fygAQpIqSjDxiyLaP-F6Y](url)

**Comment by thebezelproject** [comment] 2020-04-23 08:50
I was able to track down the masters for fatfury2/3. They have been uploaded.

**Closed** 2020-04-23 10:07 UTC

**Comment by thebezelproject** [comment] 2020-05-06 04:50
The following have been updated.
darius
darius2
ddungeon
fatfury2
fatfury3
